sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t molefeq/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true molefeq/docker-react npm run test