sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t molefeq/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true molefeq/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker_client"
  env: "DockerClient-env"
  bucket_name: "elasticbeanstalk-us-east-2-421744851502"
  bucket_path: "docker_client"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"